import Head from "next/head";
import Image from "next/image";

export default function Home() {
    return (
        <>
            <Head>
                <title>FelixPlay - Get Free HD Movies, Shows, Animes</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.png" />
            </Head>

            <h1>Hello World</h1>
        </>
    );
}
